name: Docker Image Build Workflow

on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
          - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    name: build_docker_image
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sktometometo/foundation-model-grpc-server:${{ github.ref }}