name: Docker Image Build Workflow
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    name: build_docker_image
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: sktometometo/foundation-model-grpc-server
          build-args: |
            SKIP_MODEL_DOWNLOAD=true